services:
  aerials:
    image: flashspys/nginx-static:latest
    container_name: aerials
    ports:
      - 5050:80
    volumes: 
      - ./downloads:/static/downloads
      - ./metadata/0.1.0:/static/metadata
      - ./deployment/index.html:/static/index.html
      - ./deployment/style.css:/static/style.css
      - ./deployment/nginx-cors.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s